pub type Object(a) {
  O2(a, a)
  O3(a, a, a)
  O4(a, a, a, a)
  O5(a, a, a, a, a)
  O6(a, a, a, a, a, a)
  O7(a, a, a, a, a, a, a)
  O8(a, a, a, a, a, a, a, a)
  O9(a, a, a, a, a, a, a, a, a)
  S2(String, a)
  S3(String, a, a)
  S4(String, a, a, a)
  S5(String, a, a, a, a)
  S6(String, a, a, a, a, a)
  S7(String, a, a, a, a, a, a)
  S8(String, a, a, a, a, a, a, a)
  S9(String, a, a, a, a, a, a, a, a)
}
